load("@rules_elixir//:elixir_release.bzl", "elixir_release")
load("@rules_elixir//:ex_unit_test.bzl", "ex_unit_test")
load("@rules_elixir//:mix_app.bzl", "mix_app")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "srcs",
    srcs = glob(
        [
            "lib/**",
            "config/**",
            "priv/**",
            "mix.exs",
            "mix.lock",
        ],
        allow_empty = True,
    ),
)

mix_app(
    name = "erlang_app",
    srcs = [":srcs"],
    app_name = "agentboard",
    deps = [
        "@hexpm//:ash",
        "@hexpm//:ash_events",
        "@hexpm//:ash_oban",
        "@hexpm//:ash_paper_trail",
        "@hexpm//:ash_phoenix",
        "@hexpm//:ash_postgres",
        "@hexpm//:bandit",
        "@hexpm//:castore",
        "@hexpm//:ecto_sql",
        "@hexpm//:jason",
        "@hexpm//:oban",
        "@hexpm//:phoenix",
        "@hexpm//:phoenix_ecto",
        "@hexpm//:phoenix_html",
        "@hexpm//:phoenix_live_view",
        "@hexpm//:postgrex",
        "@hexpm//:simple_sat",
        "@rules_elixir//elixir",
    ],
)

elixir_release(
    name = "release",
    srcs = [":srcs"],
    out = "agentboard-release.tar.gz",
    app = ":erlang_app",
    mix_env = "prod",
    overlays = {":static": "priv/static"},
)

genrule(
    name = "assets",
    srcs = [
        "assets/app.js",
        "@hex_phoenix//:browser_js",
        "@hex_phoenix_html//:browser_js",
        "@hex_phoenix_live_view//:browser_js",
    ],
    outs = ["static_build/assets/app.js"],
    cmd = """
      set -euo pipefail
      "$(location @esbuild_linux_x86_64//:bin)" web/assets/app.js --bundle --minify --outdir="$(RULEDIR)/static_build/assets" \
        --alias:phoenix="$$PWD/$(location @hex_phoenix//:browser_js)" \
        --alias:phoenix_html="$$PWD/$(location @hex_phoenix_html//:browser_js)" \
        --alias:phoenix_live_view="$$PWD/$(location @hex_phoenix_live_view//:browser_js)"
    """,
    tools = ["@esbuild_linux_x86_64//:bin"],
)

genrule(
    name = "styles",
    srcs = [
        "assets/app.css",
        "assets/app.js",
    ] + glob(["lib/agentboard_web/**/*.ex"]),
    outs = ["static_build/assets/app.css"],
    cmd = "$(location @tailwindcss_linux_x64//file) --input=$(location assets/app.css) --output=$@ --minify",
    tools = ["@tailwindcss_linux_x64//file"],
)

genrule(
    name = "static",
    srcs = [
        ":assets",
        ":styles",
    ],
    outs = ["agentboard-static.tar.gz"],
    cmd = "tar -czf $@ -C $(RULEDIR)/static_build assets",
)

ex_unit_test(
    name = "rate_limits_test",
    size = "small",
    srcs = ["test/rate_limits_test.exs"],
    data = ["test/test_helper.exs"],
    elixir_opts = ["-r", "test/test_helper.exs"],
    deps = [":erlang_app"],
)

filegroup(
    name = "format_srcs",
    srcs = glob([
        "lib/**/*.ex",
        "config/*.exs",
        "priv/repo/migrations/*.exs",
        "test/*.exs",
        "mix.exs",
    ]),
)
